### ISSUE TITLE
[Task] 로그인, 회원가입 세부 기능 구현

### ISSUE THREAD

**Issue by outclassstudio** [codestates/Schedule24-7#117]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
- 서버 API통한 로그인 회원가입 세부기능 구현

### TODO
- [ ] 로그인 기능 구현
- [ ] 회원가입 기능 구현
- [ ] Job3

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
