### ISSUE TITLE
[Task] 배포: AWS 코드 파이프라인 환경변수 수정

### ISSUE THREAD

**Issue by imdex1009** [codestates/Schedule24-7#124]
### ISSUE Type
- [ ] SR
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
메일러 모듈 사용에 따른 환경변수 조정

### TODO
- [ ] parameter store 수정
- [ ] appspec scripts 수정

### Estimated time
- [ ] `0.5h`
- [x] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [ ] `3h`
