### ISSUE TITLE
[Task] schedule 생성 알고리즘 개발

### ISSUE THREAD

**Issue by imdex1009** [codestates/Schedule24-7#128]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
스케줄을 생성하기 위한 알고리즘 작성

### TODO
- [ ] 사전 준비 함수
- [ ] 관련 데이터 임시 보관 형태
- [ ] 알고리즘 작성

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
