### ISSUE TITLE
[Task] 로그아웃 기능 구현 및 세부기능 추가, CSS 디테일 보강

### ISSUE THREAD

**Issue by outclassstudio** [codestates/Schedule24-7#138]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
- 로그아웃 기능 구현 및 세부기능 추가, CSS 디테일 보강

### TODO
- [ ] 로그아웃 기능구현
- [ ] 마이 페이지 일부수정 및 세부기능 추가
- [ ] 헤더 일부 수정 

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
