### ISSUE TITLE
[Task] 비밀번호 수정 및 회원탈퇴 기능 구현

### ISSUE THREAD

**Issue by outclassstudio** [codestates/Schedule24-7#146]
### ISSUE Type
- [ ] SR
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
- 비밀번호 수정 및 회원탈퇴 기능 구현

### TODO
- [ ] 비밀번호 수정 기능 구현
- [ ] 회원탈퇴 기능 구현

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [ ] `3h`
