### ISSUE TITLE
[MeetingLog] 테스트 계정관련

### ISSUE THREAD

**Issue by imdex1009** [codestates/Schedule24-7#159]
### Title
- 테스트 계정 구현 관련
### Process (기능 관련 프로세스)
- 애플리케이션 내에서 체험하기 클릭시 테스트 계정 생성(백엔드)
- 테스트 계정 생성 후, 토큰 발급 및 응답으로 테스트 계정 여부 클라이언트 전달
- 로그아웃 시 해당 테스트 계정 데이터 삭제
### Task 
**프론트엔드**
- [ ] 테스트 계정 인식될 경우 마이페이지 비활성
- [ ] 체험하기 버튼 내 테스트 계정 진입 API 요청 삽입
- [ ] 로그아웃 시 관련 API 요청 삽입
@heokiro  @outclassstudio 

**백엔드**
- [ ] 테스트 계정을 생성하기 위한 더미데이터 마련
- [ ] 토큰 발급 시에 테스트 계정 여부 적용
- [ ] 테스트 계정 로그아웃 요청 API 작성 ⇒ 테스트 계정 데이터 삭제

@SiwooPak
