### ISSUE TITLE
[Task] GroupPage 반응형 CSS 구현

### ISSUE THREAD

**Issue by heokiro** [codestates/Schedule24-7#180]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
그룹페이지 반응형 CSS 구현

### TODO
- [ ] GroupMemeberPage 반응형 CSS 구현
- [ ] GroupInfoPage 반응형 CSS 구현
- [ ] GroupConditionPage 반응형 CSS 구현

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
