### ISSUE TITLE
[Task] Swagger 전체 적용

### ISSUE THREAD

**Issue by SiwooPak** [codestates/Schedule24-7#194]
### ISSUE Type
- [ ] SR
- [X] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
- restapi의 User쪽의 일부분만 Swagger 적용된 부분, auth, group, schedule에도 적용

### TODO
- [x] User API의 테스트 계정쪽
- [ ] Auth API 전체
- [x] Schdule API 전체
- [x] Group API 전체

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [x] `2h`
- [ ] `2.5`
- [ ] `3h`
