### ISSUE TITLE
[Task] CSS 모바일 뷰 개선(Schedule, MainPage, MyPage)

### ISSUE THREAD

**Issue by outclassstudio** [codestates/Schedule24-7#203]
### ISSUE Type
- [ ] SR
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
- CSS 모바일 뷰 개선

### TODO
- [ ] Schedule CSS 개선
- [ ] MainPage CSS 개선
- [ ] MyPage CSS 개선

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [ ] `3h`
