### ISSUE TITLE
[Task] Main 페이지 구현

### ISSUE THREAD

**Issue by outclassstudio** [codestates/Schedule24-7#23]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
- Main 페이지 구현

### TODO
- [ ] Main 페이지 프레임 구현
- [ ] Main 페이지 기능 구현

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
