### ISSUE TITLE
[Task] Group 관련 API 기능 구현

### ISSUE THREAD

**Issue by SiwooPak** [codestates/Schedule24-7#28]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
그룹 조회 , 추가, 수정, 삭제 기능 구현

### TODO
- [x] 그룹에 대한 정보 전체 조회 기능 구현
- [x] 그룹 추가 및 생성 기능(그룹명, 그룹에 대한 부가 설명, 그룹이모지 등등) 구현
- [x] 그룹 수정 기능(그룹명, 그룹에 대한 부가 설명, 그룹이모지 등등) 구현
- [x] 해당 그룹에 대한 정보 전체 삭제 기능 구현

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [x] `2h`
- [ ] `2.5`
- [ ] `3h`
