### ISSUE TITLE
[Task] GroupInfo 페이지 구현

### ISSUE THREAD

**Issue by heokiro** [codestates/Schedule24-7#29]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
그룹의 기본정보를 확인하고 수정할 수 있는 GroupInfo 페이지 구현

### TODO
- [x]  GroupInfo 페이지 프레임 구현
- [x]  GroupInfo 페이지 기능 구현
- [x]  GroupInfo 페이지 CSS 구현

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
