### ISSUE TITLE
[Task] ViewSchedule 페이지 CSS구현

### ISSUE THREAD

**Issue by outclassstudio** [codestates/Schedule24-7#41]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
- ViewSchedule 페이지 CSS구현

### TODO
- [ ] ViewSchedule 페이지 조회 모드 CSS구현
- [ ] JViewSchedule 페이지 관리 모드 CSS구현
- [ ] Job3

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
