### ISSUE TITLE
[Task] Condition 관련 기능 API 구현

### ISSUE THREAD

**Issue by SiwooPak** [codestates/Schedule24-7#42]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
근무 스케쥴을 자동으로 짤 때 필요한 조건의 추가, 수정, 삭제 기능 구현

### TODO
- [x] 그룹의 근무 조건 추가 기능 구현
- [x] 그룹의 근무 기존의 조건 수정 기능 구현
- [x] 그룹의 기존의 근무 조건 삭제 기능 구현 

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [x] `2h`
- [ ] `2.5`
- [ ] `3h`
