### ISSUE TITLE
[Task] CSS 제반사항 세팅

### ISSUE THREAD

**Issue by outclassstudio** [codestates/Schedule24-7#45]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
- Styled Component를 활용한 CSS 제반사항 세팅, 반응형 페이지 기본 세팅

### TODO
- [ ] 디스플레이 기본 프레임 세팅(그리드, 플렉스 모델 적용)
- [ ] 반응형 페이지 기본 세팅

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
