### ISSUE TITLE
[Task] 체험 계정 관련 기능 구현

### ISSUE THREAD

**Issue by SiwooPak** [codestates/Schedule24-7#48]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
체험 계정 관련 기능 구현

### TODO
- [x] 체험계정 생성 API
- [x] 체험계정 삭제 API

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [ ] `3h`
