### ISSUE TITLE
[Task] Docker 배포

### ISSUE THREAD

**Issue by SiwooPak** [codestates/Schedule24-7#49]
### ISSUE Type
- [ ] SR
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
도커에 관련된 설정 파일 작성 및 연동

### TODO
- [x] 도커에 관련된 설정 파일 작성
- [x] 도커 이미지화시키고 배포해보기

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
