### ISSUE TITLE
[Task] Header 컴포넌트 구현

### ISSUE THREAD

**Issue by heokiro** [codestates/Schedule24-7#51]
### ISSUE Type
- [ ] SR
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
Header 컴포넌트 구현

### TODO
- [x] Header 영역 프레임 잡기
- [x] 반응형으로 디스플레이 크기에 따라 2가지 형태의 Header 구현 

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [x] `2h`
- [ ] `2.5`
- [ ] `3h`
