### ISSUE TITLE
[Task] 스키마 설계

### ISSUE THREAD

**Issue by heokiro** [codestates/Schedule24-7#8]
### ISSUE Type
- [x] SR
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
DB 스키마 다이어그램 설계

### TODO
- [x] 기획 프로토타입을 기준으로 스키마테이블 설계
- [x] 테이블간 관계 설계

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [x] `2h`
- [ ] `2.5`
- [ ] `3h`
