### ISSUE TITLE
[Task] API 문서 작성

### ISSUE THREAD

**Issue by heokiro** [codestates/Schedule24-7#9]
### ISSUE Type
- [x] SR
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Detail
swagger를 이용한 API 문서 작성

### TODO
- [ ] API 요청시 전달해줘야할 헤더, 바디, 파라미터 등 세팅
- [ ] API 응답시 전달해줘야할 데이터, 메시지 등 세팅

### Estimated time
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5`
- [x] `3h`
